service: selenium-layer

provider:
    name: aws
    runtime: python3.6
    timeout: 300

layers:
    selenium:
        path: selenium
        CompatibleRuntimes: [
            "python3.6"
        ]
    chromedriver:
        path: chromedriver
        description: chrome driver layer
        CompatibleRuntimes: [
            "python3.6"
        ]
    beautifulsoup:
        path: beautifulsoup
        CompatibleRuntimes: [
            "python3.6"
        ]
    requests:
        path: requests
        CompatibleRuntimes: [
            "python3.6"
        ]
resources:
    Outputs:
        SeleniumLayerExport:
            Value:
                Ref: SeleniumLambdaLayer
            Export:
                Name: SeleniumLambdaLayer
        ChromedriverLayerExport:
            Value:
                Ref: ChromedriverLambdaLayer
            Export:
                Name: ChromedriverLambdaLayer
        BeautifulsoupLayerExport:
            Value:
                Ref: BeautifulsoupLambdaLayer
            Export:
                Name: BeautifulsoupLambdaLayer
        RequestsLayerExport:
            Value:
                Ref: RequestsLambdaLayer
            Export:
                Name: RequestsLambdaLayer